//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServicioTarjetas_3C2023
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emisor
    {
        public int EMI_CODIGO { get; set; }
        public string EMI_DESCRIPCION { get; set; }
        public string EMII_PREFIJO { get; set; }
        public int EMI_NUMERO_DIGITOS { get; set; }
    }
}
