//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServicioTarjetas_3C2023
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Tarjetas_3C2023Entities : DbContext
    {
        public Tarjetas_3C2023Entities()
            : base("name=Tarjetas_3C2023Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Emisor> Emisors { get; set; }
        public virtual DbSet<Tarjeta> Tarjetas { get; set; }
    }
}
